title: Erle Zhu
email: erlerzhu@gmail.com
description: Personal homepage of Erle Zhu, PhD student at Tsinghua University.
baseurl: ""
url: ""
markdown: kramdown
permalink: /blog/:title/
timezone: Asia/Shanghai

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

author:
  name: Erle Zhu
  location: Beijing, China
  affiliation: Tsinghua University
  scholar: https://scholar.google.com/citations?user=z5GT6QsAAAAJ&hl=zh-CN
  github: https://github.com/Lez-3f

navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
